"""
Commande pour générer une invitation à partir d'un ID serveur
"""

import discord
from discord.ext import commands
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))
from utils.embeds import ModdyResponse, ModdyColors
from config import COLORS


class InviteCommand(commands.Cog):
    """Génère une invitation pour un serveur"""

    def __init__(self, bot):
        self.bot = bot

    async def cog_check(self, ctx):
        """Vérifie que l'utilisateur est développeur"""
        return self.bot.is_developer(ctx.author.id)

    @commands.command(name="invite", aliases=["inv", "createinvite"])
    async def generate_invite(self, ctx, server_id: str = None):
        """
        Génère une invitation pour un serveur à partir de son ID

        Usage: invite [server ID]
        """

        if not server_id:
            embed = discord.Embed(
                title="<:link:1401600607949422683> Generate Server Invite",
                description=(
                    "**Usage:** `invite [server ID]`\n\n"
                    "Generates a temporary invite link for the specified server.\n\n"
                    "**Requirements:**\n"
                    "• The bot must be in the server\n"
                    "• The bot must have 'Create Invite' permission\n\n"
                    "**Invite Settings:**\n"
                    "• Max age: 1 hour\n"
                    "• Max uses: 1\n"
                    "• Unique: Yes"
                ),
                color=COLORS["info"]
            )
            await ctx.send(embed=embed)
            return

        # Vérifie que c'est bien un ID numérique
        if not server_id.isdigit():
            await ctx.send("<:undone:1398729502028333218> Invalid server ID. Please provide a numeric ID.")
            return

        server_id = int(server_id)

        # Cherche le serveur
        guild = self.bot.get_guild(server_id)

        if not guild:
            await ctx.send(f"<:undone:1398729502028333218> Server `{server_id}` not found or bot is not in this server.")
            return

        # Vérifie les permissions
        if not guild.me.guild_permissions.create_instant_invite:
            await ctx.send(
                f"<:undone:1398729502028333218> The bot doesn't have the 'Create Invite' permission in **{guild.name}**."
            )
            return

        try:
            # Trouve un canal approprié pour créer l'invitation
            target_channel = None

            # Essaie d'abord le canal système
            if guild.system_channel and guild.system_channel.permissions_for(guild.me).create_instant_invite:
                target_channel = guild.system_channel
            else:
                # Sinon cherche le premier canal texte où le bot peut créer une invitation
                for channel in guild.text_channels:
                    if channel.permissions_for(guild.me).create_instant_invite:
                        target_channel = channel
                        break

            if not target_channel:
                await ctx.send(
                    f"<:undone:1398729502028333218> No suitable channel found in **{guild.name}** to create an invite."
                )
                return

            # Crée l'invitation
            invite = await target_channel.create_invite(
                max_age=3600,      # 1 heure
                max_uses=1,        # 1 utilisation
                unique=True,       # Unique
                reason=f"Invite generated by developer {ctx.author} via invite command"
            )

            # Embed de succès
            embed = discord.Embed(
                title=f"<:done:1398729525277229066> Invite Created",
                description=f"Invitation generated for **{guild.name}**",
                color=COLORS["success"]
            )

            embed.add_field(
                name="<:link:1401600607949422683> Invite Link",
                value=f"[Click here to join]({invite.url})\n`{invite.url}`",
                inline=False
            )

            embed.add_field(
                name="<:settings:1398729549323440208> Settings",
                value=(
                    f"**Channel:** {target_channel.mention}\n"
                    f"**Max age:** 1 hour\n"
                    f"**Max uses:** 1\n"
                    f"**Code:** `{invite.code}`"
                ),
                inline=False
            )

            embed.add_field(
                name="<:info:1401614681440784477> Server Info",
                value=(
                    f"**ID:** `{guild.id}`\n"
                    f"**Members:** `{guild.member_count}`\n"
                    f"**Created:** <t:{int(guild.created_at.timestamp())}:R>"
                ),
                inline=False
            )

            if guild.icon:
                embed.set_thumbnail(url=guild.icon.url)

            embed.set_footer(
                text=f"Generated by {ctx.author}",
                icon_url=ctx.author.display_avatar.url
            )

            await ctx.send(embed=embed)

            # Log l'action si le système de log existe
            if log_cog := self.bot.get_cog("LoggingSystem"):
                await log_cog.log_command(ctx, "invite", {
                    "server": guild.name,
                    "server_id": guild.id,
                    "invite_code": invite.code
                })

        except discord.Forbidden:
            await ctx.send(
                f"<:undone:1398729502028333218> Missing permissions to create an invite in **{guild.name}**."
            )
        except discord.HTTPException as e:
            await ctx.send(
                f"<:undone:1398729502028333218> An error occurred while creating the invite: {e}"
            )
        except Exception as e:
            await ctx.send(
                f"<:undone:1398729502028333218> Unexpected error: {e}"
            )


async def setup(bot):
    await bot.add_cog(InviteCommand(bot))
