"""
Developer Tools - Slash commands for testing and debugging
Only accessible to developers
"""

import discord
from discord import app_commands
from discord.ext import commands
import logging

logger = logging.getLogger('moddy.dev_tools')


class DevTools(commands.Cog):
    """Developer tools for testing and debugging"""

    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(
        name="testerror",
        description="[DEV ONLY] Generate a test error to verify error handling systems"
    )
    @app_commands.allowed_installs(guilds=True, users=True)
    @app_commands.allowed_contexts(guilds=True, dms=True, private_channels=True)
    async def test_error(self, interaction: discord.Interaction):
        """
        Test command to generate an error and verify that:
        1. The error is logged properly
        2. The error is sent to Discord error channel
        3. The error is stored in the database
        4. The error is captured by Sentry (if configured)
        5. The user receives a proper error message

        This command is only accessible to developers.
        """
        # Check if user is a developer
        if not self.bot.is_developer(interaction.user.id):
            await interaction.response.send_message(
                "❌ This command is only accessible to developers.",
                ephemeral=True
            )
            return

        # Log that a test error is being triggered
        logger.info(f"🧪 Test error triggered by {interaction.user} ({interaction.user.id})")

        # Send a message before triggering the error
        await interaction.response.send_message(
            "🧪 **Generating test error...**\n\n"
            "This will trigger the error handling system. You should receive an error message shortly.\n\n"
            "**What to check:**\n"
            "• Error message is displayed to you\n"
            "• Error is logged in console\n"
            "• Error is sent to Discord error channel\n"
            "• Error is stored in database\n"
            "• Error is captured in Sentry (if configured)",
            ephemeral=True
        )

        # Intentionally raise an error to test the error handling system
        # This will be caught by the error handler and processed normally
        raise RuntimeError(
            "This is a test error generated by /testerror command. "
            "If you see this, the error handling system is working correctly!"
        )


async def setup(bot):
    await bot.add_cog(DevTools(bot))
